services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: notification
      POSTGRES_USER: notification
      POSTGRES_PASSWORD: notification
      TZ: Asia/Seoul
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5432:5432"

  adminer:
    image: adminer:4
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
      TZ: Asia/Seoul
    ports:
      - "18080:8080"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    environment:
      - TZ=Asia/Seoul
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - TZ=Asia/Seoul
    volumes:
      - ./docker/observability/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
